# docker build --progress=plain . -t fep3fastddsplugin:latest -f ./build_profiles/armv8_docker/dockerfile 
# sudo apt-get install qemu binfmt-support qemu-user-static # Install the qemu packages
# docker run --rm --privileged multiarch/qemu-user-static --reset -p yes # This step will execute the registering scripts
# sudo docker run  -i --platform linux/arm64  --rm -t fep3fastddsplugin:latest /bin/bash

FROM --platform=linux/arm64 arm64v8/ubuntu:20.04 AS base

ENV DISPLAY=:99.0
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update --allow-releaseinfo-change
RUN apt install git g++-9 python3 python3-pip -y
RUN pip3 install "conan==1.59.0" --use-pep517
RUN apt install wget -y
WORKDIR /root
RUN wget https://github.com/Kitware/CMake/releases/download/v3.26.3/cmake-3.26.3-linux-aarch64.sh
RUN chmod +x ./cmake-3.26.3-linux-aarch64.sh
RUN ./cmake-3.26.3-linux-aarch64.sh  --skip-license 
ENV PATH "$PATH:/root/bin"

COPY ./ /root/fep3_fast_dds_plugin
WORKDIR /root/fep3_fast_dds_plugin
# RUN conan create ./thirdparty/dev_essential/conanfile.py /_@_ -pr ./build_profiles/linux_armv8_gcc9 --build=missing
# RUN conan create ./thirdparty/fast_dds/conanfile.py /_@_ -pr build_profiles/linux_armv8_gcc9 --build=missing
# RUN conan create thirdparty/fastdds-cxx/conanfile.py /_@_ -pr build_profiles/linux_armv8_gcc9
# RUN conan create thirdparty/fep3_participant/conanfile.py /_@_ -pr build_profiles/linux_armv8_gcc9
# RUN conan create thirdparty/fep3_system/conanfile.py /_@_ -pr build_profiles/linux_armv8_gcc9
# RUN conan create thirdparty/fep3_base_utilities/conanfile.py /_@_ -pr build_profiles/linux_armv8_gcc9
# RUN conan create thirdparty/fep3_sdk/conanfile.py /_@_ -pr build_profiles/linux_armv8_gcc9
# RUN conan create . -pr build_profiles/linux_armv8_gcc9

# To export with conan - run a local server and use:
# "url": "http://host.docker.internal:9300" for the host conan server as url config
# now log in and
# conan remote add local http://host.docker.internal:9300 false
# conan user demo -p=demo -r=local
# list all local packages and upload them
# conan search | while read -r line; do command conan upload "$line" -r=local --force --all -c; done
